config/routes.rb
Rails.application.routes.draw do

  get 'files/download' => 'files#download'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: "users/registrations" }
  resources :notes
  root to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.has_role? :user
      can :manage, :all
    else
      can :read, :all # guest user (not logged in)
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, presence: true, length: { minimum: 4 }
  
  mount_uploaders :content, ContentUploader

  validates_integrity_of  :content
  validates_processing_of :content

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes, dependent: :destroy

  rolify
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable,
         :validatable, :authentication_keys => [:login]
  
  validates :username,:presence => true,
            :uniqueness => {:case_sensitive => false}, 
            length: {maximum: 255}

  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions.to_hash).first
    end
  end

  after_create :assign_default_role

  def assign_default_role
    add_role(:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :notice => exception.message
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def download
    send_file(params[:path])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.order("created_at DESC").where(user_id: current_user.id)
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :body, {content: []}, :content_cache)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_params

  def create
    super
  end

  protected

  def configure_permitted_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :birthdate, :phone, :username,
               :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:login, :username, :email, :password, :remember_me)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :birthdate, :phone, :username,
               :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def preview_or_default_image(media)
    if media.content_type.starts_with? 'image'
      media.thumb.url.to_s
    elsif media.content_type.starts_with? 'application'
      'thumb_doc.jpg'
    elsif media.content_type.starts_with? 'audio'
      'thumb_audio.jpg'
    else media.content_type.starts_with? 'video'
      'thumb_video.png'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'New Note', new_note_path, data: { 'no-turbolink'=>true} %></li>
          <li><%= link_to 'NOTES', notes_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= "#{current_user.username}" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Registration', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div id="content">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<div class="form">
  <%= form_for @note, html: { multipart: true } do |f| %>
    <% if @note.errors.any? %>
      <div class="alert alert-success">
        <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.cktext_area :body, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
    </div><br>

    <div class="field">
      <%= f.label :content %>
      <% if @note.content? %>
        <% @note.content.each do |media| %>
          <table>
            <tr>
              <td><%= image_tag(preview_or_default_image(media)) %></td>
              <td><%= link_to "#{media.file.identifier}", files_download_path(path: media.url.to_s) %></td>
            </tr>
          </table>
        <% end %>
      <% end %>
      <%= f.file_field :content, multiple: true %>
      <%= f.hidden_field :content_cache %>
      <p>
      </p>
    </div><br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div id="edit">
  <h1>Editing Note</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @note %> |
  <%= link_to 'Back', notes_path %>
</div><br>

app/views/notes/index.html.erb
<div id="notes"><br>
  <h1>Listing my Notes</h1>

    <% @notes.each do |note| %>
      <div class="note">
        <h2><%= link_to note.title, note %></h2>
        <%= sanitize(note.body[0,200]) %><br>
        <td><%= link_to 'Edit', edit_note_path(note), class: "btn btn-success", 
                                        data: { 'no-turbolink'=>true} %></td>
        <td><%= link_to 'Destroy', note, method: :delete, 
                                        class: "btn btn-danger" %></td><br><br>
      </div>
    <% end %>
</div>

app/views/notes/new.html.erb
<div id="new"><br>
  <h1>New Note</h1>

  <%= render 'form' %>

  <%= link_to 'Back', notes_path %>
</div><br>

app/views/notes/show.html.erb
<div id="show">
  <h2>
    <%= @note.title %>
  </h2>
  <p>
    <%= sanitize(@note.body) %>
  </p>
  <p>
    <strong>Content:</strong>
    <% @note.content.map do |media| %>
      <table>
        <tr>
          <td><%= image_tag(preview_or_default_image(media)) %></td>
          <td><%= link_to "#{media.file.filename}", files_download_path(path: media.current_path.to_s) %></td>
        </tr>
      </table>
    <% end %>
  </p>

  <%= link_to 'Edit', edit_note_path(@note), data: { 'no-turbolink'=>true} %> |
  <%= link_to 'Back', notes_path %>
</div><br>

app/views/welcome/index.html.erb
<div id="cv">
  <div class="img"><%= image_tag("profile.jpg") %></div>
  <div class="info"><br>
    <h2>Ruby on Rails Developer</h2>
    <table>
      <tr>
        <th>Name:</th>
        <th>Sasha Stipanenko</th>
      </tr>
      <tr>
        <th>Age:</th>
        <th>11th April 1990 year</th>
      </tr>
      <tr>
        <th>City:</th>
        <th>Donetsk</th>
      </tr>
      <tr>
        <th>Email:</th>
        <th>alex.stipanenko@gmail.com</th>
      </tr>
      <tr>
        <th>Phone:</th>
        <th>(050) 789-58-95</th>
      </tr>
      <tr>
        <th>GitHub profile:</th>
        <th>https://github.com/satoshy</th>
      </tr>
    </table>
  </div>

  <div class="education">
    <h3>Education:</h3>
    <p>Donetsk National University</p>
    <p>Physics-Technology Faculty</p>
    <p>M.S. Physics (2007 - 2012)</p>
  </div>

  <div class="skills">
    <h3>Summary of skills:</h3>
    <p>&bull; Ruby</p>
    <p>&bull; Ruby on Rails</p>
    <p>&bull; HTML, CSS, JS</p>
    <p>&bull; Databases: MySQL, PostgreSQL</p>
  </div>

  <div class="foreign-lang">
    <h3>Languages:</h3>
    English (Pre-intermediate), Russian (Intermediate), Ukrainian (Intermediate);
  </div>

  <div class="experience">
    <h3>Profesional experience:</h3>
    <p>
      At the moment I am studying the following books:
      "Programming Ruby (Dave Thomas)" and "Practical Object-Oriented Design in Ruby (Sandi Metz)". In GitHub profile you can see my projects on Ruby on Rails (simple blog and ecommerce shop).
    </p>
  </div><br>
</div>